package xyz.gustycube.redstoneLimits;

import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.io.IOException;
import java.util.UUID;

public class YamlStorageManager implements StorageManager {

    private final RedstoneLimits plugin;
    private File dataFile;
    private FileConfiguration dataConfig;

    public YamlStorageManager(RedstoneLimits plugin) {
        this.plugin = plugin;
    }

    @Override
    public void initialize() throws Exception {
        dataFile = new File(plugin.getDataFolder(), "playerdata.yml");

        if (!dataFile.exists()) {
            if (!dataFile.getParentFile().exists()) {
                dataFile.getParentFile().mkdirs();
            }
            try {
                // Create an empty file if it doesn't exist
                dataFile.createNewFile();

                // Create a basic structure and save it
                FileConfiguration emptyConfig = new YamlConfiguration();
                emptyConfig.options().header(
                        "RedstoneLimit Player Data\n" +
                                "This file stores the counts of redstone components and hoppers for each player.\n" +
                                "DO NOT EDIT THIS FILE MANUALLY!\n" +
                                "Format:\n" +
                                "<uuid>:\n" +
                                "  redstone: <count>\n" +
                                "  hoppers: <count>"
                );
                emptyConfig.save(dataFile);
            } catch (IOException e) {
                throw new Exception("Could not create playerdata.yml", e);
            }
        }

        dataConfig = YamlConfiguration.loadConfiguration(dataFile);
    }

    @Override
    public void close() {
        try {
            dataConfig.save(dataFile);
        } catch (IOException e) {
            plugin.getLogger().severe("Could not save playerdata.yml");
            e.printStackTrace();
        }
    }

    @Override
    public PlayerData loadPlayerData(UUID playerUUID) {
        String uuidString = playerUUID.toString();

        if (!dataConfig.contains(uuidString)) {
            return new PlayerData(playerUUID);
        }

        int redstoneCount = dataConfig.getInt(uuidString + ".redstone", 0);
        int hopperCount = dataConfig.getInt(uuidString + ".hoppers", 0);

        return new PlayerData(playerUUID, redstoneCount, hopperCount);
    }

    @Override
    public void savePlayerData(PlayerData playerData) {
        String uuidString = playerData.getPlayerUUID().toString();

        dataConfig.set(uuidString + ".redstone", playerData.getRedstoneCount());
        dataConfig.set(uuidString + ".hoppers", playerData.getHopperCount());

        try {
            dataConfig.save(dataFile);
        } catch (IOException e) {
            plugin.getLogger().severe("Could not save playerdata.yml");
            e.printStackTrace();
        }
    }
}